#!/bin/bash
# Save Claude session notes on session end
# 1. Writes metadata to S3 (/mnt/s3-thanudev12/session/)
# 2. Extracts conversation context into AgentContext repo

# Read hook input from stdin
INPUT=$(cat)

# Extract session info
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // "unknown"')
CWD=$(echo "$INPUT" | jq -r '.cwd // "unknown"')

# --- Part 1: S3 metadata (date-partitioned, per-session folder) ---
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H-%M-%S)
YYYY=$(date +%Y)
YYYYMM=$(date +%Y%m)
YYYYMMDD=$(date +%Y%m%d)

# Project hierarchy = full working-directory path as nested folders
# e.g. /home/thanumahee/dev/data-alchemy -> home/thanumahee/dev/data-alchemy
PROJECT=$(printf '%s' "$CWD" | sed -e 's#^/*##' -e 's#/*$##')
[ -z "$PROJECT" ] && PROJECT="unknown"

# Layout: session/claude/<pwd hierarchy>/YYYY/YYYYMM/YYYYMMDD/<DATE>_<TIME>_<shortid>/
BASE_DIR="/mnt/s3-thanudev12/session/claude"
SESSION_DIR="${BASE_DIR}/${PROJECT}/${YYYY}/${YYYYMM}/${YYYYMMDD}/${DATE}_${TIME}_${SESSION_ID:0:8}"
NOTES_FILE="${SESSION_DIR}/notes.md"
TRANSCRIPT_PATH="${SESSION_DIR}/transcript.jsonl"

mkdir -p "$SESSION_DIR"

# Multi-user: make shared ancestor dirs world-writable + sticky (like /tmp),
# so any user can extend the tree under their own branch. Best-effort; only
# succeeds on dirs this user owns (i.e. the ones just created).
d="$(dirname "$SESSION_DIR")"
while [ -n "$d" ] && [ "$d" != "/" ]; do
    chmod 1777 "$d" 2>/dev/null || true
    [ "$d" = "$BASE_DIR" ] && break
    d="$(dirname "$d")"
done

cat > "$NOTES_FILE" << EOF
# Claude Session Notes
**Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Session ID:** ${SESSION_ID}
**Working Directory:** ${CWD}

## Session Summary
- Session ended at $(date '+%H:%M:%S')
- Session folder: ${SESSION_DIR}
- Transcript: ${TRANSCRIPT_PATH}

---
*Auto-generated by Claude Code SessionEnd hook*
EOF

# --- Part 2: Extract conversation + copy transcript beside notes.md ---
# Resolve the extractor next to this script (repo is the single source of truth).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXTRACTOR="${SCRIPT_DIR}/extract-session.py"
# Prefer the system python (no dependency on any user's home dir).
if [ -x /usr/bin/python3 ]; then PYTHON=/usr/bin/python3; else PYTHON=$(command -v python3); fi
if [ -f "$EXTRACTOR" ]; then
    # Pass the per-session folder so the transcript lands beside notes.md
    "$PYTHON" "$EXTRACTOR" "$SESSION_ID" "$CWD" "$SESSION_DIR" 2>/dev/null &
    # Run in background so it doesn't block session exit
    # Give it a moment to start, then let it finish independently
    disown
fi

exit 0
